name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run all

  e2e: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: count
        uses: ./
      - run: echo 'Found ${{ steps.count.outputs.counted }} callers'
